/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NavFooter: typeof import('./src/components/NavFooter.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongCreate: typeof import('./src/components/SongCreate.vue')['default']
    SongEdit: typeof import('./src/components/SongEdit.vue')['default']
    VariatsioonCreate: typeof import('./src/components/VariatsioonCreate.vue')['default']
    VariatsioonEdit: typeof import('./src/components/VariatsioonEdit.vue')['default']
  }
}
