/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/error': RouteRecordInfo<'/error', '/error', Record<never, never>, Record<never, never>>,
    '/esitusloendid/': RouteRecordInfo<'/esitusloendid/', '/esitusloendid', Record<never, never>, Record<never, never>>,
    '/forbidden': RouteRecordInfo<'/forbidden', '/forbidden', Record<never, never>, Record<never, never>>,
    '/kogumikud/': RouteRecordInfo<'/kogumikud/', '/kogumikud', Record<never, never>, Record<never, never>>,
    '/laulud/': RouteRecordInfo<'/laulud/', '/laulud', Record<never, never>, Record<never, never>>,
    '/laulud/[id]': RouteRecordInfo<'/laulud/[id]', '/laulud/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/signin': RouteRecordInfo<'/signin', '/signin', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/signup-confirm': RouteRecordInfo<'/signup-confirm', '/signup-confirm', Record<never, never>, Record<never, never>>,
    '/uus-laul': RouteRecordInfo<'/uus-laul', '/uus-laul', Record<never, never>, Record<never, never>>,
  }
}
